alibaba/arthas

boot/src/main/java/com/taobao/arthas/boot/Bootstrap.java
boot/src/main/java/com/taobao/arthas/boot/ProcessUtils.java

When users accidentally enter a non-integer, prompt instead of printing
stack trace.
```
[INFO] Process 3027 already using port 3658
[INFO] Process 3027 already using port 8563
* [1]: 3027 jar
a
Exception in thread "main" java.util.InputMismatchException
at java.util.Scanner.throwFor(Scanner.java:913)
at java.util.Scanner.next(Scanner.java:1534)
at java.util.Scanner.nextInt(Scanner.java:2164)
at java.util.Scanner.nextInt(Scanner.java:2123)
at com.taobao.arthas.boot.ProcessUtils.select(ProcessUtils.java:71)
at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:252)
```

More user-friendly prompts when selecting pid.

---

common/src/main/java/com/taobao/arthas/common/JavaVersionUtils.java
core/src/main/java/com/taobao/arthas/core/Arthas.java

1. 我觉得既然有了`JavaVersionUtils`工具类，那么在获取Java版本时尽量要使用它
2. `java`和`jps`都是JAVA的二进制文件，是否能统一它们的查找过程？

Improve get Java version

---

bin/as.sh

1. 我觉得`as.sh`的行为应该和`arthas-boot`保持一致，虽然我们可以通过环境变量和java命令找到可能的`JAVA_HOME`，但实际上我们并不能肯定它就是；和`arthas-boot`一样，我们在java9以下的版本中，在找`tools.jar`文件的同时，修正我们之前找到的那个`JAVA_HOME`
2. `$(call_jps) | grep -v sun.tools.jps.Jps`这条语句会报`command not found`错误，原因是会把$(call_jps)的结果作为命令来执行
Fix #381

Fix #381: improve find tools.jar logic

---

site/src/site/sphinx/docker.md
site/src/site/sphinx/en/docker.md

之前的链接是需要登录docker hub才能访问，修改为不用登录就能访问的链接

Change docker hub repository url.

---

testcase/src/main/java/com/alibaba/arthas/Test.java

long或者Long初始赋值时，必须使用大写的L，不能是小写的l，小写容易跟数字1混淆，造成误解。

Use uppercase L to declare variables

---

common/src/main/java/com/taobao/arthas/common/OSUtils.java

删除重复的Mac OS判断分支

---

site/src/site/sphinx/mc.md

https://alibaba.github.io/arthas/mc.html  中点击`redefine`跳转失败（404），跳转地址为：https://alibaba.github.io/arthas/redefine.md

mc文档中redefine超链接跳转问题

---

bin/as-service.bat
bin/as.bat
site/src/site/sphinx/en/manual-install.md
site/src/site/sphinx/manual-install.md

简单介绍as-service.bat的处理流程：
1）as-service.bat -pid/-port  直接指定pid或者通过端口查找pid，自动创建名为arthas的windows服务，设置服务的执行文件路径为 as-service.bat -service pid，然后启动arthas服务。--interact 参数可以开启服务UI交互模式，方便定位错误。
2）arthas服务启动后，根据-service参数可以指定当前是运行在服务中，通过 start  as.bat <pid> 启动注入进程。这里要注意，经过测试，必须使用start启动新的子进程才能启动arthas，否则失败。
解析一下windows权限问题：
1）桌面会话隔离问题
windows service运行的程序的会话ID为0，远程桌面登录或者本地桌面的会话ID则为1之后的值，可以在任务管理器“查看” - “选择列”菜单选择“会话ID”。经过测试，发现只有相同会话ID的Java进程才能通过JVM接口进行操作，jps/jconsole/arthas只能列出同一个会话的其他Java进程。所以要注入以windows service运行的Java进程也就需要以服务方式启动arthas。

support inject into java process of windows service

---

core/src/main/java/com/taobao/arthas/core/shell/cli/CompletionUtils.java

```
public class MathGame {
private static Random random = new Random();
public int illegalArgumentCount = 0;
public static void main(String[] args) throws InterruptedException {
while (true) {
TimeUnit.SECONDS.sleep(1);
}
}
}
```

fix method completion when class only has one method

---

core/src/main/java/com/taobao/arthas/core/command/express/ClassLoaderClassResolver.java

If ognl express's class cann't find, throws java.lang.NullPointerException, it confusing.
Fix to throw java.lang.ClassNotFoundException.

fix class loader npe

---

core/src/main/java/com/taobao/arthas/core/config/Configure.java

When I was trying to attach arthas to an Elasticsearch instance and find which permission i should grant to Elasticsearch, nothing printed out but `telnet port is 0, skip bind telnet server.` and `http port is 0, skip bind http server.` in `${user.home}/logs/arthas/arthas.log`.
I added some code to `AgentBootstrap#bind` method to see what `args` and `configure` is, I got `args` is ok and `configure` is empty. It is because method `Configure#toConfigure` catch `IllegalAccessException` throwed by`ArthasReflectUtils#set` method and return empty `Configure` instance.

Throw IllegalAccessException out when set filed failed.

---

core/src/main/java/com/taobao/arthas/core/shell/impl/ShellImpl.java

1. 钉钉群里很多人反馈，进入arthas之后，sc无法看到项目中编写的类
2. 最后发现启动时进入了错误的jvm进程
3. 模仿bash，在提示符 $ 前增加pid信息，时刻知道自己在哪个进程里

命令行提示符增加pid提示

---

core/src/main/java/com/taobao/arthas/core/util/ThreadLocalWatch.java

修复monitor命令中 监控调用链上的多个method时，RT时间不准的问题

---

core/src/main/java/com/taobao/arthas/core/shell/impl/ShellServerImpl.java

After attached and quit from shell, there is a thread with default name in application's JVM.
So, give a specific name to the thread.

rename the thread

---

core/src/main/java/com/taobao/arthas/core/command/monitor200/WatchCommand.java

其目的为让watch命令和trace/stack默认必选参数一致，方便替换方式切换,
并可减少使用者的健盘输入，方便使用者，以提高生产力:)

Set default value for the express argument of the watch command

---

core/src/main/java/com/taobao/arthas/core/shell/cli/impl/CliTokenImpl.java
core/src/test/java/com/taobao/arthas/core/shell/cli/impl/CliTokenImplTest.java

fix [#1151](https://github.com/alibaba/arthas/issues/1151)
修复后的实际运行结果：

fix issue 1151 管道符“｜”与前后一条命令之间没有空格，不能正确识别

---

bin/as.sh
boot/src/main/java/com/taobao/arthas/boot/Bootstrap.java
boot/src/main/java/com/taobao/arthas/boot/ProcessUtils.java
client/src/main/java/com/taobao/arthas/client/IOUtil.java
client/src/main/java/com/taobao/arthas/client/TelnetConsole.java

#1115 #1118 增加二次检查telnet端口和pid是否匹配，解决部分场景下Arthas注入进程混乱的问题。
主要原因：
1）部分场景存在权限问题导致通过系统命令无法检测到telnet端口已经被使用的情况
2）按照正常流程尝试注入目标进程没有报错（调用注入agent成功，因为端口冲突问题，新的Arthas实例启动失败）
3）as.sh脚本和arthas-boot.jar按照流程连接了原来的另外一个进程的Arthas实例，出现注入混乱问题。
解决办法：
1) 在第二步向目标进程注入agent之前，通过arthas-client.jar 连接目标telnet端口并执行session命令，如果连接成功并获取到结果，则提示用户错误信息，并终止执行。
2) 极端场景出现arthas-client 探测被挂起的问题已经处理，arthas-client添加命令执行超时参数--execution-timeout  2000
已测试指定的telnet port是另外一个arthas进程、某个http服务端口、22端口、remote debug端口4种情况。

double check telnet port and pid before attach agent

---

core/src/main/resources/io/termd/core/term/terminfo.src

尝试解决这个 [issue:1186](https://github.com/alibaba/arthas/issues/1186)
思路：
之前加载com/alibaba/middleware/termd-core/1.1.7.9/termd-core-1.1.7.9.jar!/io/termd/core/term/terminfo.src 消耗较大内存，但是只用到了其中的xterm device，故抽取了xterm device配置信息，替换jar中的terminfo.src

only load xterm device, memory optimization

---

tutorials/katacoda/arthas-advanced-cn/arthas-boot.md
tutorials/katacoda/arthas-advanced-cn/finish.md
tutorials/katacoda/arthas-advanced-cn/start-demo.md
tutorials/katacoda/arthas-advanced-cn/web-console.md
tutorials/katacoda/arthas-advanced-en/arthas-boot.md
tutorials/katacoda/arthas-advanced-en/start-demo.md
tutorials/katacoda/arthas-advanced-en/web-console.md
tutorials/katacoda/arthas-basics-cn/arthas-boot.md
tutorials/katacoda/arthas-basics-cn/finish.md
tutorials/katacoda/arthas-basics-en/arthas-boot.md

#847 修复迁移过程中链接问题
@hengyunabc 
另外请注意arthas-advanced-cn/start-demo.md和arthas-advanced-en/start-demo.md中第7行的下载链接地址需要另外更改。
这样之后您就可以删除原来的仓库了。
此外我还注意到[这个教程](https://www.katacoda.com/arthas/courses/arthas-cn)是无法访问的，原因是因为arthas-cn-pathway.json命名有误，建议删除arthas-cn-pathway.json和arthas-pathway.json这两个文件。
另外一个更复杂的解决方案：可以将下列文件夹和文件重命名，然后修复链接问题：
arthas-advanced-cn -> arthas-cn-advanced
arthas-advanced-en -> arthas-en-advanced
arthas-basics-cn -> arthas-cn-basics
arthas-basics-en -> arthas-cn-basics
arthas-pathway.json -> arthas-en-pathway

修复链接问题 fix link issues

---

core/pom.xml
pom.xml

following Maven's guide https://maven.apache.org/guides/mini/guide-reproducible-builds.html
I could not check that the result was fully reproducible, because I can't run rpm
but if you follow instruction to check a rebuild against initial build, I'm pretty sure that most of the output content is reproducible: I'm interested to know what remains not reproducible (I suppose the rpm/deb files...)

make build Reproducible (mostly)

---

core/src/main/java/com/taobao/arthas/core/command/monitor200/ProfilerCommand.java

Call `process.end()` before return

fix `profiler actions` command does not end

---

core/src/main/java/com/taobao/arthas/core/command/klass100/OgnlCommand.java
core/src/main/java/com/taobao/arthas/core/command/model/OgnlModel.java
core/src/main/java/com/taobao/arthas/core/command/view/ClassLoaderView.java
core/src/main/java/com/taobao/arthas/core/command/view/OgnlView.java
core/src/main/java/com/taobao/arthas/core/util/ClassLoaderUtils.java
core/src/main/java/com/taobao/arthas/core/util/ClassUtils.java
site/src/site/sphinx/en/ognl.md
site/src/site/sphinx/ognl.md

添加通过class name指定classloader的特性，解决katacoda 教程中不能自动指定classloader hash的问题，普通SpringBoot场景可以通过`--classLoaderClass org.springframework.boot.loader.LaunchedURLClassLoader` 来指定classloader。   
也可以方便用户交流及编写通用批处理脚本，大部分场景具有普适性，指定classloader class可以解决通用问题。
```
[arthas@45680]$ ognl --classLoaderClass org.springframework.boot.loader.LaunchedURLClassLoader  @org.springframework.boot.SpringApplication@logger
@Slf4jLocationAwareLog[
FQCN=@String[org.apache.commons.logging.LogAdapter$Slf4jLocationAwareLog],
name=@String[org.springframework.boot.SpringApplication],
logger=@Logger[Logger[org.springframework.boot.SpringApplication]],
]
```

classloader command support the classLoaderClass option

---

core/src/main/java/com/taobao/arthas/core/command/monitor200/ProfilerCommand.java

profiler在jfr录制，必须在start的时候就指定文件路径，否则无法录制成功

修复profiler命令仅指定参数 --format jfr 时无法录制成功问题

---

.gitignore

添加原因是eclipse安装了pmd plugin后会自动生成.pmd，为防止git误操作应该忽略此文件

ignore .pmd for git

---

tutorials/katacoda/case-http-api-cn/session-interaction.md
tutorials/katacoda/case-http-api-en/session-interaction.md

在Terminal 4中执行拉取命令时会因为session_id和consumer_id不存在而报错，所以新增提示用户输入
https://www.katacoda.com/hollowman/scenarios/case-http-api-cn

Fix ID doesn't exist in T4

---

bin/as.bat

as.bat脚本有错误导致arthas启动失败

---

agent/src/main/java/com/taobao/arthas/agent334/AgentBootstrap.java
core/src/main/java/com/taobao/arthas/core/server/ArthasBootstrap.java
core/src/main/java/com/taobao/arthas/core/shell/session/impl/SessionManagerImpl.java
core/src/test/java/com/taobao/arthas/core/advisor/EnhancerTest.java

fix issues: 
https://github.com/alibaba/arthas/issues/1514 
https://github.com/alibaba/arthas/issues/1513
* Improve arthas stop logic, fix #1513 
* Clean resources when http port bind failed

Improve arthas stop logic (#1513, #1514)

---

core/src/main/java/com/taobao/arthas/core/command/monitor200/DashboardCommand.java
core/src/main/java/com/taobao/arthas/core/command/monitor200/ThreadCommand.java
core/src/main/java/com/taobao/arthas/core/command/view/DashboardView.java
core/src/main/java/com/taobao/arthas/core/command/view/ViewRenderUtil.java
core/src/main/java/com/taobao/arthas/core/util/StringUtils.java
core/src/main/java/com/taobao/arthas/core/util/ThreadUtil.java

*  Replace String.format() with string concat/builder, reducing lots of Formatter objects
* Improve ThreadUtil.getThreads() 
* Improve text-ui ScreenBuffer and LabelElement (https://github.com/alibaba/text-ui/pull/2)
test command: `dashboard -i 1000 -n 10`
`DashboardView.draw()` profile result statistics:
| Item | Before | After | Reduce | 
| -| -| -| -|
| Object Count | 184303 |67873 | 63% |
| Object Size | 7732976 | 3321216| 57% |
| Object Allocations | 19 K/s | 7.3 K/s | 61% |
**Before:**
**After:**

Reduce small objects generated by dashboard commands

---

pom.xml

as checked in Reproducible Central https://github.com/jvm-repo-rebuild/reproducible-central#com.taobao.arthas:arthas-all, reproducibility of latest releases has improved (with 3.4.4 having been done from a dirty Git workspace...) but after having checked 3.4.5, there are 2 remaining issues:
1. there are 2 remaining non-reproducible Git properties, that this PR removes
2. something during the rebuild changes pom.xml xsd from http to https
Changing xsd to https://maven.apache.org/xsd/maven-4.0.0.xsd in source tree could be a good idea, I don't know if there are any objections

improve reproducibility of the build

---

core/src/main/java/com/taobao/arthas/core/advisor/ArthasMethod.java
core/src/main/java/com/taobao/arthas/core/env/MutablePropertySources.java
core/src/main/java/com/taobao/arthas/core/util/LogUtil.java
core/src/main/java/com/taobao/arthas/core/util/ObjectUtils.java
core/src/main/java/com/taobao/arthas/core/view/Ansi.java
tunnel-server/src/main/java/com/alibaba/arthas/tunnel/server/TunnelSocketFrameHandler.java

1.Remove some invalid codes;
2.The implementation of the `removeIfPresent` method in `MutablePropertySources` class is optimized. In LinkedList, the remove method will judge whether the element is included or not, so the optimization will reduce one for loop operation;
3.Fixed a log printing error in the `TunnelSocketFrameHandler` class.

Some code optimization

---

site/src/site/sphinx/en/trace.md
site/src/site/sphinx/trace.md

Update the wiki, adding that trace does not support `trace java.lang.Thread getName` description

wiki: not support 'trace java.lang.Thread getName'

---

bin/as.bat
bin/as.sh

很多APM工具、调试工具，都是通过设置环境变量 `JAVA_TOOL_OPTIONS` 来实现相关功能（比如[Aliyun ARMS](https://help.aliyun.com/document_detail/85906.html#title-v0c-bbr-dn0)、[GCP Cloud Profiler](https://spring-gcp.saturnism.me/app-dev/observability/profiling#agent-configurations)）。
最终用户在通过`./as.sh`启动arthas时，也会加载APM agent。
但使用Arthas的人，即没有必要管理Arthas的性能、没有必要调试Arthas内部代码，这个行为也增加了arthas的启动时间。
所以在`./as.sh`脚本中，忽略`JAVA_TOOL_OPTIONS`环境变量，以便更快的启动、更方便的使用。

remove env JAVA_TOOL_OPTIONS

---

core/src/main/java/com/taobao/arthas/core/server/ArthasBootstrap.java

原bug，可以看到指定配置文件路径后，参数传递正常，但是通过resolvePlaceholders无法拿到路径。
故修改为arthasEnvironment.getProperty(CONFIG_LOCATION_PROPERTY); 之后便可以正常获取路径参数。

FIX(arthas.core):修复javaagent指定arthas.properties路径加载错误

---

core/src/main/resources/com/taobao/arthas/core/http/web-console.js
tunnel-server/src/main/resources/static/web-console.js

原webConsole中初始化xterm时screenReaderMode参数为true，导致webConsole右侧滚动条不可鼠标点击拖动，同时鼠标右击也不可复制粘贴。鉴于screenReaderMode使用场景目前几乎没有，希望默认改为false提升用户体验。

Set the screenReaderMode of xterm to false

---

core/src/main/resources/com/taobao/arthas/core/http/web-console.js
tunnel-server/src/main/resources/static/web-console.js

WebConsole的xterm终端目前只支持向上回滚1000条数据行数，经常出现执行几条命令后，前面数据就不可见的问题，另外其他终端都不止1000条的回滚行数。所以添加了用户可配置的scrollback参数。

WebConsole支持配置向上回滚的数据行数

---

core/src/main/java/com/taobao/arthas/core/command/klass100/DumpClassCommand.java
core/src/main/java/com/taobao/arthas/core/command/klass100/RetransformCommand.java

change RetransformCommand and DumpClassCommand limit option description to match @DefaultValue annotation
description annotation says the default is 5 but defaultValue annotation set it's default to 50

change RetransformCommand and DumpClassCommand limit option description to match @DefaultValue annotation

---

site/docs/.vuepress/client.js
site/docs/.vuepress/config.js
site/docs/.vuepress/configs/head/head.js
site/docs/.vuepress/configs/head/index.js
site/docs/.vuepress/configs/index.js
site/docs/.vuepress/configs/navbar/en.js
site/docs/.vuepress/configs/navbar/index.js
site/docs/.vuepress/configs/navbar/zh.js
site/docs/.vuepress/configs/sidebar/en.js
site/docs/.vuepress/configs/sidebar/index.js
site/docs/.vuepress/configs/sidebar/zh.js
site/docs/.vuepress/plugins/vuepress-plugin-loadVersion/index.js
site/docs/.vuepress/theme/components/Badge.vue
site/docs/.vuepress/theme/components/HomeHero.vue
site/docs/.vuepress/theme/components/NavbarBrand.vue
site/docs/.vuepress/theme/components/RightMenu.vue
site/docs/.vuepress/theme/index.js
site/package-lock.json
site/package.json
site/yarn.lock

1. 放弃 CommonJS，迁移到 ESM
2. 修改部分导入路径
3. DocSearch 插件修复回车选择无法正常跳转
适配 [vuepress2 beta51](https://github.com/vuepress/vuepress-next/blob/main/CHANGELOG.md#200-beta51-2022-08-28)

chore(docs): adapted vuepress2 beta51

---

core/src/main/java/com/taobao/arthas/core/util/SearchUtils.java

Fixes #2277
问题原因并非issue中描述的“必须提供至少特定数量字符”才能正确匹配，而是当匹配的类中有jvm根类加载器加载的类时（即null），会抛NullPointException。

fix issue:sc command throws NPE.

---

web-ui/arthasWebConsole/ui/src/arthas.d.ts
web-ui/arthasWebConsole/ui/src/components/NavHeader.vue
web-ui/arthasWebConsole/ui/src/machines/perRequestMachine.ts
web-ui/arthasWebConsole/ui/src/router/index.ts
web-ui/arthasWebConsole/ui/src/stores/fetch.ts

* null loop <-> loop for async
* 全局挂载轮询的变量只有这两个状态
* pull_results轮询需要的启动依赖于异步的行为，比如dashboard
* 当长期不使用这类异步的命令，consumer会失活，只能让用户手动重新init session
* null loop <-> loop for keep alive <-> loop for async
* 全局挂载轮询的变量多了一个中间的状态
* init session了以后会处于该状态，每隔一段较长的时间pull_results

perf(web ui):keep alive consumer

---

core/src/main/java/com/taobao/arthas/core/command/klass100/SearchClassCommand.java
core/src/main/java/com/taobao/arthas/core/util/ClassLoaderUtils.java
site/docs/doc/sc.md
site/docs/en/doc/sc.md

Fixes #2283 
**Feature**: enhance the `sc` command. This PR will make `sc` can search class according to the value of target class's `ClassLoader#toString()`.
**Usage**: `sc -cs {the value of ClassLoader#toString()} {other param}` or `sc --classLoaderStr {the value of ClassLoader#toString()} {other param}`.

fix issue: support ClassLoader#toString() for sc command.

---

boot/src/main/java/com/taobao/arthas/boot/Bootstrap.java

```
telnetPortPid = findProcessByTelnetClient(arthasHomeDir.getAbsolutePath(),
```
method `findProcessByTelnetClient` may find  telnetPortPid , we should check  `telnetPortPid == pid` again.

fix attach doublecheck

---

client/src/main/java/com/taobao/arthas/client/TelnetConsole.java

I'm confused that why return STATUS_ERROR at  line 218;
maybe it should retrun STATUS_OK?

fix TelnetConsole#process() return status

---

boot/src/main/java/com/taobao/arthas/boot/DownloadUtils.java

It is not necessary to hard-code the read length。
It is not friendly to modify the data array length

update DownloadUtils: clear hardcode

---

core/src/main/java/com/taobao/arthas/core/shell/term/impl/http/HttpRequestHandler.java

Add http header connection close

---

site/docs/en/doc/mbean.md

The current MD file only mentions the `n` command without giving an actual example. If people want to monitor mbeans for a long time it's unclear how to do it. The command in this commit shows an example on how to combine `-i` along with `'-n`

Add -n command example to mbean commands

---

pom.xml

To fix [CVE-2023-20861](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-20861) .

Bump spring-boot from 2.7.0 to 2.7.11

---

.github/workflows/build-async-profiler.yml
common/src/main/java/com/taobao/arthas/common/OSUtils.java
core/src/main/java/com/taobao/arthas/core/command/monitor200/ProfilerCommand.java

在 arthas cli 命令行，可使用 profiler 命令支持生成应用热点的火焰图，背后使用了 async-profiler 提供支持。在 Linux 环境下，async-profiler 默认只对 x86-64、aarch64 这两种操作系统架构提供了 glibc 版的动态链接库文件：
```txt
libasyncProfiler-linux-x64.so
libasyncProfiler-linux-arm64.so
```
但是在基于 musl libc 实现的 Alpine Linux 环境下，执行 profiler 命令会误加载到 libasyncProfiler-linux-x64.so 或者 libasyncProfiler-linux-arm64.so ，首先会提示缺少 libstdc++、libgcc 库文件，手工执行下面的命令安装后，再次执行 profiler 命令会造成应用 jvm 进程 crash :
hs_err_pid17.log
```log
Stack: [0x0000ffff60bf0000,0x0000ffff60dffac8],  sp=0x0000ffff60dfe520,  free space=2105k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libstdc++.so.6+0x1683dc]
C  [libstdc++.so.6+0xd9b9c]  std::locale::operator=(std::locale const&)+0x54
C  [libstdc++.so.6+0xd9094]  std::ios_base::_M_init()+0x4c
C …
```

为使用Alpine Linux作为Docker基础镜像的Java应用提供profiler命令支持

---

tunnel-server/src/main/java/com/alibaba/arthas/tunnel/server/AgentClusterInfo.java
tunnel-server/src/main/java/com/alibaba/arthas/tunnel/server/TunnelServer.java
web-ui/arthasWebConsole/all/tunnel/src/Agent.vue
web-ui/arthasWebConsole/all/tunnel/tunnel.d.ts

https://github.com/alibaba/arthas/issues/2572

Fix the page redirection issue of Arthas tunnel server #2572

---

.gitignore
core/src/main/java/one/profiler/AsyncProfiler.java
core/src/main/java/one/profiler/package-info.java

参考 issue #2164 中的说明，首先需要升级 one.profiler。
首先分析此包本身的差异，实质性的改动有：修改了 `getInstance` 方法，添加了 `extractEmbeddedLib` 和 `getPlatformTag` 方法，其中 `getPlatformTag` 仅被 `extractEmbeddedLib` 调用，`extractEmbeddedLib` 仅被 `getInstance` 调用。
此方法在 one.profiler 内部仅被同名无参重载方法调用。
在 ProfilerCommand 类中，此方法仅被 `profilerInstance` 调用（L249/271），且同名无参重载方法未被调用。
此方法内部，实际上仅改动了 `libPath == null` 情况的对应逻辑。L51 表示如果 jvm 进程启动时已经加载 lib，就直接返回。否则，L53\~59 尝试从类路径中获取对应平台的 lib.so，复制到一个临时文件用于加载，加载后 L58 删除临时文件。如果类路径中未事先按规则准备这些 lib 文件，那么 `extractEmbeddedLib` 方法将返回 null，此时将与旧代码行为一致，直接从操作系统库搜索路径中查找加载 lib（若未找到则抛出错误，不会返回 profiler 实例）。总而言之，这是对已有行为的扩展而不是修改。
在 ProfilerCommand.profilerInstance 方法中，在 L271 处的调用不可能传入 null 参数，因此前述改动对此无任何影响。在 L249 处的调用只有 `profiler load` 命令不加额外参数时才会向 `getInstance` 传入 null，而前述改动不会引入破坏性。

Async profiler api upgrade

---

core/src/main/java/com/taobao/arthas/core/command/monitor200/ProfilerCommand.java
site/docs/doc/profiler.md
site/docs/en/doc/profiler.md

stop action 主要涉及测试结果的输出，需处理 [profiler.sh](https://github.com/async-profiler/async-profiler/blob/32601bccd9e49adda9510a2ed79d142ac6ef0ff9/profiler.sh#L354C15-L354C15) 中 FIEL、OUTPUT、FORMAT 三个变量对应的选项。在 sh 脚本中分析结果允许输出到标准输出或文件，且与输出内容格式是完全解耦的。Arthas 的设计可能是：要求必须将分析结果保存到文件，因此在 `processStop` 方法中只要判断 file 选项为空就会指定一个默认文件名。
目前对 file 选项的捕捉本身没有问题，可以对应到 sh 中的 FILE 变量。
在 sh 中通过 `-o` 选项转换为此变量，但目前 arthas 中没有该选项，仅有一个相关的 format 选项，它仅用于构造默认文件名的后缀（未传递给 execute 方法）且只有两个可选值，【分析结果】的内容格式是让 async-profiler 通过这个后缀名推断的。在 sh 中，通过设置 OUTPUT 可以得到其他格式的输出（如 flat 等格式）。要想在 profiler command 中支持这些格式，可以将 format 选项的值也用于构造 executeArgs，将其与 sh 的 `-o` 选项对应起来。
根据 sh 脚本中的使用说明，`-o` 选项可选值为 `flat|traces|collapsed|flamegraph|tree|jfr`，且均可在 arguments.cpp 中找到详细解释，其中 flat 和 traces 可加 `[=N] ` 格式参数，在 Arthas 中，用 format 选项捕捉这些值，并为选项添加短名称 …

Upgrade "stop action" in profiler command

---

core/src/main/java/com/taobao/arthas/core/command/monitor200/ProfilerCommand.java
site/docs/doc/profiler.md
site/docs/en/doc/profiler.md

在 `ProfilerAction` 枚举类中添加 dump 即可捕获，action 排列顺序尽量与原 sh 脚本保持一致，方便后续升级。
修改 `processStop` method 使其接收多种 action，因为除了 `stop` 之外还有其他（`dump`）action 需要调用此方法。
`dump` action 的选项与 `stop` 完全一致，没有引入新的 Option。
issue #2164

Add dump action

---

core/src/main/java/com/taobao/arthas/core/command/monitor200/ProfilerCommand.java
site/docs/doc/profiler.md
site/docs/en/doc/profiler.md

在 async-profiler 的 shell 脚本中这些 ACTION 仅使用 FILE 变量构造 JVM TI 参数，且此时的 FILE 变量仅是为了指定临时文件用于输出到屏幕。因此，在 arthas 中，直接仅传递 action 到 execute 方法即可，将这三种 action 合并到一个分支中。
async-profiler 对 version ACTION 的处理有些奇怪，在 CLI 中表现为一个选项，但在 shell 脚本中却捕获为 ACTION。在 Arthas 中目前直接作为 CLI 的 action 处理，这是更合理的做法，因此虽然与上游不一致，但仍然保留这种处理。不过，注意到 version 存在 `=full` 的可选格式，shell 脚本中均采用完整格式而 arthas 目前打印的是简短格式，将其修改为 full 格式以与上游和旧版 arthas 的行为一致。
issue #2164

Upgrade profiler action: version, meminfo

---

core/src/main/java/com/taobao/arthas/core/command/monitor200/ProfilerCommand.java
site/docs/doc/profiler.md
site/docs/en/doc/profiler.md

根据Async-profiler，include，exclude参数在采样的时候是不起作用的，只在dump的时候起作用。
如果profiler start带--include，--exclude参数而stop没有带是无法排出指定包的，因此样例
```
profiler start --include 'java/*' --include 'com/demo/*' --exclude '*Unsafe.park*'
```
中的"start"应该改为"stop"

修改ProfilerCommand的错误样例

---

README.md
README_CN.md
arthas-tutorials-cn/command/dump/dump.md
arthas-tutorials-cn/command/getstatic/getstatic.md
arthas-tutorials-cn/command/jfr/arthas-boot.md
arthas-tutorials-cn/command/jfr/jfr.md
arthas-tutorials-cn/command/profiler/arthas-boot.md
arthas-tutorials-cn/command/profiler/profiler.md
arthas-tutorials-cn/command/sc/sc.md
arthas-tutorials-cn/command/sm/sm.md
arthas-tutorials-en/command/dump/dump.md
arthas-tutorials-en/command/getstatic/getstatic.md
arthas-tutorials-en/command/jfr/arthas-boot.md
arthas-tutorials-en/command/jfr/jfr.md
arthas-tutorials-en/command/profiler/arthas-boot.md
arthas-tutorials-en/command/profiler/profiler.md
arthas-tutorials-en/command/sc/sc.md
arthas-tutorials-en/command/sm/sm.md

- 修改平台名称 Katacoda 修改为 Killercoda
- 为 `jfr` 和 `profile` 命令教程添加设置账号密码

fix: update platform name in Arthas tutorials

---

core/src/main/java/com/taobao/arthas/core/command/monitor200/ProfilerCommand.java
site/docs/doc/profiler.md
site/docs/en/doc/profiler.md

添加 shell 脚本 L229 --alloc|--lock|--chunksize|--chunktime 选项。
在 async-profiler 中，"include only user-mode events" 功能对应的 JVM TI 格式参数为 alluser 但 CLI 选项为 `--all-user`（shell 脚本 [L240](https://github.com/async-profiler/async-profiler/blob/32601bccd9e49adda9510a2ed79d142ac6ef0ff9/profiler.sh#L240)）。目前 arthas 中 CLI 格式为 `--alluser`，是否考虑更换为兼容上游的格式？
另外，arthas 实现了 `--allkernel` 选项，但 async-profiler 的 README 和命令 help message 中都没有这个选项，具体原因可参考  [Why allkernel option is not in README or help message?](https://github.com/async-profiler/async-profiler/discussions/810)，是否考虑去掉该选项？
issue #2164

Upgrade action start resume part2

---

core/src/main/java/com/taobao/arthas/core/command/monitor200/ProfilerCommand.java
site/docs/doc/profiler.md
site/docs/en/doc/profiler.md

L240 --all-user 格式不一致，arthas 中为 --alluser，根据 pr #2647 讨论结果修改，并去掉 --allkernel 选项。
L243 --sched。L246 --live。
L249 --cstack|--call-graph 两个选项完全等价，仅实现前者，因为 async-profiler 的文档和 help message 中都只列出前者。
L253 begin，end。
L257 ttsp，对 begin，end 有影响，async-profiler 设计为晚出现的选项优先级高，但 Arthas 似乎无法实现此行为，决定设计为 ttsp 优先级更高。
issue #2164

Upgrade action start resume part3

---

core/src/main/java/com/taobao/arthas/core/command/view/TraceView.java
core/src/main/java/com/taobao/arthas/core/util/ThreadUtil.java

Currently, the thread id format displayed by different commands is different. For example, the thread id in the dashboard is in decimal format, and the thread id in the trace command is in hexadecimal format and does not start with `0x`, which is easy to confuse. Refer to the thread id format in the JDK stack frame. It is recommended to use decimal format uniformly.

Make thread id uniformly displayed in decimal format

---

core/src/main/java/com/taobao/arthas/core/command/klass100/DumpClassCommand.java

dump命令检测-d参数指定路径是否为目录的条件不准确，
例如路径对应的是linux的设备文件，此时就会有问题

fix directory check for DumpClassCommand

---

arthas-agent-attach/src/main/java/com/taobao/arthas/agent/attach/ArthasAgent.java

非springboot工程使用代码方式启动agent时如果要手动指定arthasHome无法生效，看了下是参数没传。

fix: agent-attach携带的arthasHome参数未生效

---

pom.xml

#2530
* Set assertj-core version to 3.24.2 in `pom.xml`

Bump AssertJ Core from 2.9.1 to 3.24.2

---

pom.xml

#2530
* Set dependency `ch.qos.logback:logback-classic` version to 1.2.12 in `pom.xml`
* Set dependency `ch.qos.logback:logback-core` version to 1.2.12 in `pom.xml`
(It seems that spring-boot 2.7.x does not work with logback 1.3.x because it uses slf4j 1.7.x instead of 2.0.x, so I haven't bumped logback to 1.3.x)

Bump logback from 1.2.11 to 1.2.12

---

core/src/main/java/com/taobao/arthas/core/command/monitor200/ProfilerCommand.java
site/docs/doc/profiler.md
site/docs/en/doc/profiler.md

L260 jfrsync，在拼接 executeArgs 时，需要放在 format 之前，否则 executeArgs 将可能使用错误的 format。即使在捕捉参数时已经做过一次处理，但如果用户重复指定 format 参数仍可修改 format 变量，所以此处拼接字符串时仍需处理且需要注意顺序。
L272 safemode，选项值的格式不明，意义不明。根据 [async-profiler 的说明](https://github.com/async-profiler/async-profiler/discussions/797)，**不需要实现此选项**。
在 async-profiler 中，check option 的处理逻辑和 start/resume 的唯一区别就是是否启动 fdtransfer，鉴于目前 Arthas 中 start/resume 并未启动 fdtransfer，所以 check action 可以直接使用 resume 的逻辑。
issue #2164

Upgrade action start resume part4

---

core/src/main/java/com/taobao/arthas/core/command/monitor200/ProfilerCommand.java
site/docs/doc/profiler.md
site/docs/en/doc/profiler.md

经过[讨论](https://github.com/alibaba/arthas/issues/2164#issuecomment-1718945907)选择方案一。在捕捉选项的部分，捕捉 timeout 和 loop 选项的分支中，检测 action 为 collect 时转换为 start。
在处理 action 的部分，当 action 为 start 时，不涉及 duration 变量的值，所以即使用户指定了 -d 选项 arthas 也不会按指定的时间结束 profiling，在这种情况下可以接收 timeout 和 loop 控制 profiling 过程；当 action 为 collect 时必然不存在 timeout 或 loop 选项，直接使用 executeArgs 方法拼接参数字符串也没有问题，并且接收 -d 选项指定的 duration 控制时间，如果未指定 duration，则仍需输入 stop 命令才能停止 profiling。
另外，删除了指定 format 为 jfr 时需要在 start 之前生成文件名的逻辑，因为目前 format 是 JVMTI 字符串的一部分。
issue #2164

Add action collect

---

memorycompiler/src/main/java/com/taobao/arthas/compiler/ClassUriWrapper.java
memorycompiler/src/main/java/com/taobao/arthas/compiler/CustomJavaFileObject.java
memorycompiler/src/main/java/com/taobao/arthas/compiler/DynamicJavaFileManager.java
memorycompiler/src/main/java/com/taobao/arthas/compiler/PackageInternalsFinder.java

Optimized the compilation speed of the memory compiler

Optimized the compilation speed of the memory compiler

---

pom.xml

Upgrade `bytekit` to `0.0.9` to load dynamical classes.
(cherry picked from commit 4dc65baf7f21012fb302e6615cda58a5d2a676fa)

Fix error of enhancing dynamically generated classes

---

memorycompiler/src/main/java/com/taobao/arthas/compiler/DynamicCompiler.java

Currently, when use arthas's DynamicCompiler compile java code will discard the LocalVariableTable. By add option -g causes the compiler to generate the LocalVariableTable attribute in the class file.

update DynamicCompiler add -g option for generate LocalVariableTable

---

core/src/main/java/com/taobao/arthas/core/command/basic1000/Base64Command.java
tunnel-client/src/main/java/com/alibaba/arthas/tunnel/client/ProxyClient.java
tunnel-client/src/main/java/com/alibaba/arthas/tunnel/client/TunnelClientSocketClientHandler.java

#2834 
1. Base64Command
2. TunnelClientSocketClientHandler
3. ProxyClient
使用netty的ByteBuf没有释放导致netty堆外内存泄漏

Release netty ByteBuf after use

---

core/src/main/java/com/taobao/arthas/core/command/klass100/ClassLoaderCommand.java

#2842 使用Map来提高查找效率：原始代码每次在buildTree方法中都需要遍历整个列表来查找子节点。可以使用一个Map来存储每个ClassLoaderVO对象的父节点名字。

optimize BuildTree of ClassLoader -t

---

boot/src/main/java/com/taobao/arthas/boot/Bootstrap.java
core/src/main/java/com/taobao/arthas/core/command/basic1000/HistoryCommand.java
core/src/main/java/com/taobao/arthas/core/command/basic1000/JFRCommand.java

typo: variable name and word error.

typo: variable name and word error.

---

core/src/main/java/com/taobao/arthas/core/shell/cli/impl/CliTokenImpl.java
core/src/test/java/com/taobao/arthas/core/shell/cli/impl/CliTokenImplTest.java

Revert "优化识别重定向" ，修复 watch等命令不支持构造函数 <init> 的问题

---

.github/workflows/build-vmtool.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml

avoid a lot of noise created by the "Progress" in build log, like
```
Downloaded from central: https://repo.maven.apache.org/maven2/org/glassfish/javax.json/1.1.4/javax.json-1.1.4.jar (129 kB at 1.8 MB/s)
Progress (1): 1.2/2.8 MB
Progress (1): 1.2/2.8 MB
Progress (1): 1.2/2.8 MB
Progress (1): 1.2/2.8 MB
Progress (1): 1.3/2.8 MB
Progress (1): 1.3/2.8 MB
...
```

mvn -ntp: no transfer progress

---

arthas-vmtool/src/main/java/arthas/VmTool.java
arthas-vmtool/src/main/java/arthas/VmToolMXBean.java
arthas-vmtool/src/main/native/src/jni-library.cpp
arthas-vmtool/src/test/java/arthas/VmToolTest.java
core/src/main/java/com/taobao/arthas/core/command/monitor200/VmToolCommand.java
site/docs/doc/vmtool.md
site/docs/en/doc/vmtool.md

malloc_trim 是排查 java 64M 问题的重要函数，参考 https://juejin.cn/post/6854573220733911048
CLOSE: https://github.com/alibaba/arthas/issues/3020

Add mallocTrim command to vmTool

---

core/src/main/java/com/taobao/arthas/core/view/ObjectView.java
core/src/test/java/com/taobao/arthas/core/view/ObjectViewTest.java

使用了错误的类型判断，所以导致 enum 枚举走了不该走的逻辑。
在 jdk 高版本 的场景下，会有问题。
ts=2025-07-17 15:58:47.327; [cost=0.03725ms] result=ERROR DATA!!! object class: class java.util.ArrayList, exception class: class java.lang.reflect.InaccessibleObjectException, exception message: Unable to make field private final java.lang.String java.lang.Enum.name accessible: module java.base does not "opens java.lang" to unnamed module @3d3762e1
这里会遍历 enum 的多个字段，会有访问性问题。

fix bug of enum obj
