core/src/main/java/com/taobao/arthas/core/command/monitor200/JvmCommand.java, core/src/main/java/com/taobao/arthas/core/util/StringUtils.java, core/src/test/java/com/taobao/arthas/core/util/StringUtilsTest.java, site/src/site/sphinx/jvm.md
=> 增加jvm命令中memory可读性

site/src/site/sphinx/en/options.md
=> translate options

core/src/test/java/com/taobao/arthas/core/util/ArrayUtilsTest.java
issue #112
add ArrayUtils test case
=> add ArrayUtils test case

core/src/main/java/com/taobao/arthas/core/command/monitor200/JvmCommand.java, site/src/site/sphinx/en/jvm.md, site/src/site/sphinx/jvm.md
1.  add `jvm` command thread related document
2.  add `jvm` command display file descriptor count
=> adjust jvm command

CONTRIBUTING_EN.md
=> contributing en

site/src/site/sphinx/en/release-notes.md
=> release-notes en

site/src/site/sphinx/en/advice-class.md
=> advice-class en

site/src/site/sphinx/en/manual-install.md
=> manual-install en

README.md
Some improvements in Grammer of Documentation
=> README-minor-changes.md

site/src/site/sphinx/en/index.md
Fixed grammatical errors and reworded portions of text for better clarity
=> Grammar and rewording for clarity

core/src/main/java/com/taobao/arthas/core/util/TokenUtils.java, core/src/test/java/com/taobao/arthas/core/util/TokenUtilsTest.java
=> bugfix&test case. #165

site/src/site/sphinx/en/stack.md, site/src/site/sphinx/en/tt.md
=> [WIP] fix some logic and descriptions issues in doc

bin/as.sh
=> bug fix when unzip not found

core/src/test/java/com/taobao/arthas/core/util/TypeRenderUtilsTest.java
=> Add tests for a couple of methods of TypeRenderUtils

core/src/test/java/com/taobao/arthas/core/testtool/TestUtils.java, core/src/test/java/com/taobao/arthas/core/util/FileUtilsTest.java
1.  add test tools
2. add test case for FiltUtils.java with test tools
=> Testcase for file utils

core/src/main/java/com/taobao/arthas/core/command/klass100/SearchClassCommand.java
=> sort sc command ouput

site/src/site/sphinx/en/index.md
@ralf0131 fixed the conflicts #229
=> fix typos in index; fix some grammatical issues; using more formal terms/usages

site/src/site/sphinx/en/async.md, site/src/site/sphinx/en/manual-install.md, site/src/site/sphinx/en/sc.md, site/src/site/sphinx/en/tt.md, site/src/site/sphinx/quick-start.md
Signed-off by: Sergio Escalante sergioescala@gmail.com
=> Fixing typos

core/src/main/java/com/taobao/arthas/core/command/monitor200/ThreadCommand.java, core/src/main/java/com/taobao/arthas/core/config/FeatureCodec.java, core/src/main/java/com/taobao/arthas/core/util/StringUtils.java, core/src/main/java/com/taobao/arthas/core/util/TypeRenderUtils.java, core/src/main/java/com/taobao/arthas/core/util/reflect/FieldUtils.java
replace toArray(new T[size]) with toArray(new T[0]) for better performance
https://shipilev.net/blog/2016/arrays-wisdom-ancients/#_conclusion
=> Optimize toArray

site/src/site/sphinx/en/mc.md
=> see issue #509（mc文档中redefine超链接跳转问题 ）

core/src/main/java/com/taobao/arthas/core/command/klass100/ClassLoaderCommand.java
=> Modify a broken Comment

.travis.yml, core/src/main/java/com/taobao/arthas/core/command/monitor200/DashboardCommand.java, core/src/main/java/com/taobao/arthas/core/command/monitor200/DashboardInterruptHandler.java, core/src/main/java/com/taobao/arthas/core/command/monitor200/MonitorAdviceListener.java, core/src/main/java/com/taobao/arthas/core/server/ArthasBootstrap.java, core/src/main/java/com/taobao/arthas/core/shell/impl/ShellServerImpl.java, core/src/main/java/com/taobao/arthas/core/shell/system/impl/GlobalJobControllerImpl.java, core/src/main/java/com/taobao/arthas/core/util/Decompiler.java, core/src/main/java/com/taobao/arthas/core/util/NetUtils.java, core/src/main/java/com/taobao/arthas/core/util/StringUtils.java, core/src/main/java/com/taobao/arthas/core/util/UserStatUtil.java, core/src/main/java/com/taobao/arthas/core/view/Ansi.java, pom.xml
This commit applies [p3c-pmd](https://github.com/alibaba/p3c) plugin/rules, and fixes/ignores all violations of piority 1 (mandatory).
=> Apply pmd plugin and fix/ignore broken styles

bin/as-service.bat, bin/as.bat
as-service.bat 以非阻塞方式启动arthas服务，修复JAVA_HOME判断等bug
=> avoid blocking while start arthas service

core/src/main/java/com/taobao/arthas/core/advisor/ReflectAdviceListenerAdapter.java, core/src/main/java/com/taobao/arthas/core/command/monitor200/MonitorAdviceListener.java
=> Fix typo (#604)

core/src/main/java/com/taobao/arthas/core/command/klass100/GetStaticCommand.java
=> fix getstatic description

boot/src/test/java/com/taobao/arthas/boot/DownloadUtilsTest.java
I've analysed your codebase and noticed that com.taobao.arthas.boot.DownloadUtils is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).
Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important.
=> Add unit tests for com.taobao.arthas.boot.DownloadUtils

core/src/main/java/com/taobao/arthas/core/command/monitor200/TimeTunnelCommand.java, core/src/main/java/com/taobao/arthas/core/shell/command/CommandProcess.java, core/src/main/java/com/taobao/arthas/core/shell/system/impl/ProcessImpl.java
fix timetunnel replay code and improve output.
=> fix timetunnel

core/src/main/java/com/taobao/arthas/core/command/klass100/JadCommand.java
=> jad complete method name

agent/src/main/java/com/taobao/arthas/agent/AgentBootstrap.java, boot/pom.xml, core/src/main/java/com/taobao/arthas/core/advisor/AdviceWeaver.java, core/src/main/java/com/taobao/arthas/core/advisor/InvokeTraceable.java, core/src/main/java/com/taobao/arthas/core/command/monitor200/AbstractTraceAdviceListener.java, core/src/main/java/com/taobao/arthas/core/command/monitor200/TraceAdviceListener.java
help me review~
[#653](https://github.com/alibaba/arthas/issues/653)
=> trace line number support

memorycompiler/src/main/java/com/taobao/arthas/compiler/DynamicJavaFileManager.java
‘if’ expression should have { }.
=> Alibaba Coding Specification

core/src/main/java/com/taobao/arthas/core/command/klass100/SearchClassCommand.java, core/src/main/java/com/taobao/arthas/core/command/klass100/SearchMethodCommand.java
- 在原来的命令基础上加上-c命令支持
sc -d可以拿到classLoaderHash
sc -c hashcode -d xxx.xxx就可以精确获取类信息
- sm -d的 展示classLoaderHash 随后给pr
=> sc sm 命令 加上-c命令支持

boot/src/main/java/com/taobao/arthas/boot/DownloadUtils.java, common/src/main/java/com/taobao/arthas/common/JavaVersionUtils.java, core/src/main/java/com/taobao/arthas/core/command/klass100/ClassLoaderCommand.java, core/src/main/java/com/taobao/arthas/core/command/klass100/JadCommand.java
What the commit entail is essentially doing some code clean up including but not limited to the following: 
1. Some renaming for the method name so it feels like better English 
2. Remove some duplicate code 
3. Some Java constant renaming
4. Some unused import removal.
=> clean up the code a little bit by following Uncle Bob's clean code guide

boot/src/main/java/com/taobao/arthas/boot/ProcessUtils.java
Benign method renaming, rename Jsp back to Jps.
=> Rename ProcessUtils#isJspProcess() to isJpsProcess() just to avoid confusion

.travis.yml, packaging/pom.xml
This Pull request is for creating the RPM package for arthas.
for testing the package run
mvn clean install
note - rpm should be installed on the system to build the package on systems other than fedora/rhel
this will create the rpm inside /packaging/target directory which can be installed by rpm/yum
=> support RPM package

site/src/site/sphinx/en/install-detail.md
Documented the installation instructions for Arthas Debian and Fedora packages
=> Added installation instructions for Debian and fedora packages

site/src/site/sphinx/options.md
=> 更正result保存日志的路径。

tunnel-server/src/main/java/com/alibaba/arthas/tunnel/server/TunnelSocketFrameHandler.java, tunnel-server/src/main/resources/static/web-console.js
针对如果输入agentId没有注册上的场景，尝试去连接一个不存在的agentId，后端给出这样的信息，给前端提示
=> add alert error message

packaging/pom.xml
bumped the jdeb version to 1.8
=> updated jdeb plugin

common/src/main/java/com/taobao/arthas/common/AnsiLog.java, common/src/main/java/com/taobao/arthas/common/IOUtils.java, common/src/main/java/com/taobao/arthas/common/JavaVersionUtils.java, common/src/main/java/com/taobao/arthas/common/OSUtils.java, common/src/main/java/com/taobao/arthas/common/PidUtils.java, common/src/main/java/com/taobao/arthas/common/SocketUtils.java, common/src/main/java/com/taobao/arthas/common/UsageRender.java
Add private constructors to some of the util class in common package as doesn't look like client should be able to instantiate them.
=> Add private constructors to util class

core/src/main/java/com/taobao/arthas/core/command/BuiltinCommandPack.java, core/src/main/java/com/taobao/arthas/core/command/basic1000/TeeCommand.java, core/src/main/java/com/taobao/arthas/core/shell/command/internal/StdoutHandler.java, core/src/main/java/com/taobao/arthas/core/shell/command/internal/TeeHandler.java, site/src/site/sphinx/en/tee.md, site/src/site/sphinx/tee.md
=> Add tee command for pipes

site/src/site/sphinx/quick-start.md
=> 质因式 -> 质因数

pom.xml
Update fastjson version for security reason
https://help.aliyun.com/noticelist/articleid/1060253179.html
=> Update dependency version of fastjson

agent/src/main/java/com/taobao/arthas/agent/AgentBootstrap.java, core/src/main/java/com/taobao/arthas/core/command/monitor200/ThreadCommand.java, tunnel-server/src/main/resources/application.properties
Dear hengyunabc, 
As a new committer, I found some minor points that could be further enhanced:
1 AgentBootstrap.java
if (!arthasLogDir.exists()) {
arthasLogDir.mkdirs();
}
if (!arthasLogDir.exists()) {
// #572
arthasLogDir = new File(System.getProperty("java.io.tmpdir") + File.separator + "logs" + File.separator+ "arthas" + File.separator);
The if (!arthasLogDir.exists()) { condition appears twice and thus I merged them into one to clean code.
2 spring boot application.properties
In order to benefit future committers, I added more comments by referring the spring boot official guide.
3 ThreadCommand.java
states = new HashSet(8); I used State.values().length to replace the hard code value 8.
If there is any inappropriateness, please help to correct.
=> Three minor code enhancements

site/src/site/sphinx/async.md, site/src/site/sphinx/en/async.md
异步任务 增加说明，不想退出artahs 进程，文档补充一下
=> 异步任务 增加说明，不想退出artahs 进程

.gitignore
以忽略批量修改pom版本生成的备份文件
ie:
```
mvn versions:set -DnewVersion=xxx
```
=> chore(.gitignore): add ignore pom.xml.versionsBackup

agent/src/main/java/com/taobao/arthas/agent3/AgentBootstrap.java
Avoid append spy jar to BootstrapClassLoader multiple times. fix #996
=> Avoid append spy jar to BootstrapClassLoader multiple times. fix #996

pom.xml
=> Update fastjson version

core/src/main/java/com/taobao/arthas/core/shell/system/impl/GlobalJobControllerImpl.java
clear job reference from timer  when cancel task.
=> fix issue #1189, clear job reference from timer

core/src/main/java/com/taobao/arthas/core/shell/cli/impl/CliTokenImpl.java
优化管道字符处理，支持前后粘‘|’字符，但不支持无空格的情况，主要原因是为了兼容非标准的写法：`trace -E classA|classB methodA|methodB`，不能强制根据'|'分割命令。
supported:
1) thread| grep xxx
[thread|, grep]  -> [thread, |, grep]
2) thread |grep xxx
[thread, |grep] -> [thread, |, grep]
unsupported:
3) thread|grep xxx
4) trace -E  classA|classB methodA|methodB|grep classA
=> #1151 fix pipe char '|' problem

boot/src/main/java/com/taobao/arthas/boot/DownloadUtils.java, boot/src/test/java/com/taobao/arthas/boot/DownloadUtilsTest.java
disable xml xxe feature
> from https://blog.spoock.com/2018/10/23/java-xxe/
=> disable xml xxe feature

core/src/main/java/com/taobao/arthas/core/command/klass100/SearchMethodCommand.java
print search method process failed class name,  also help locate trace/watch failures #730
=> #730 print sm process failed class name

CONTRIBUTING.md, README.md, site/src/site/sphinx/en/advanced-use.md, site/src/site/sphinx/en/async.md, site/src/site/sphinx/en/batch-support.md, site/src/site/sphinx/en/classloader.md, site/src/site/sphinx/en/commands.md, site/src/site/sphinx/en/download.md, site/src/site/sphinx/en/getstatic.md, site/src/site/sphinx/en/groovy.md, site/src/site/sphinx/en/index.md, site/src/site/sphinx/en/install-detail.md, site/src/site/sphinx/en/keymap.md, site/src/site/sphinx/en/quick-start.md
=> docs: removed typos and fixes grammatical errors

tunnel-client/src/main/java/com/alibaba/arthas/tunnel/client/ForwardClientSocketClientHandler.java
=> NPE avoidance & code refactor

bytekit/src/main/java/com/taobao/arthas/bytekit/asm/MethodProcessor.java, bytekit/src/test/java/com/taobao/arthas/bytekit/asm/interceptor/InlineWhileTest.java
fix inline for/while statement
=> fix iinc inst var in inline method (#1262)

bytekit/src/main/java/com/taobao/arthas/bytekit/asm/interceptor/annotation/AtEnter.java, bytekit/src/main/java/com/taobao/arthas/bytekit/asm/interceptor/annotation/AtExceptionExit.java, bytekit/src/main/java/com/taobao/arthas/bytekit/asm/interceptor/annotation/AtExit.java, bytekit/src/main/java/com/taobao/arthas/bytekit/asm/interceptor/annotation/AtFieldAccess.java, bytekit/src/main/java/com/taobao/arthas/bytekit/asm/interceptor/annotation/AtInvoke.java, bytekit/src/main/java/com/taobao/arthas/bytekit/asm/interceptor/annotation/AtInvokeException.java, bytekit/src/main/java/com/taobao/arthas/bytekit/asm/interceptor/annotation/AtLine.java, bytekit/src/main/java/com/taobao/arthas/bytekit/asm/interceptor/annotation/AtSyncEnter.java, bytekit/src/main/java/com/taobao/arthas/bytekit/asm/interceptor/annotation/AtSyncExit.java, bytekit/src/main/java/com/taobao/arthas/bytekit/asm/interceptor/annotation/AtThrow.java, bytekit/src/main/java/com/taobao/arthas/bytekit/asm/interceptor/annotation/InterceptorParserUtils.java
extract createInterceptorProcessor() function, reduce redundant code.
=> extract createInterceptorProcessor() function, reduce redundant code

tutorials/katacoda/command-version-cn/arthas-boot.md, tutorials/katacoda/command-version-cn/arthas-demo.md, tutorials/katacoda/command-version-cn/finish.md, tutorials/katacoda/command-version-cn/index.json, tutorials/katacoda/command-version-cn/intro.md, tutorials/katacoda/command-version-cn/version.md, tutorials/katacoda/command-version-en/arthas-boot.md, tutorials/katacoda/command-version-en/arthas-demo.md, tutorials/katacoda/command-version-en/finish.md, tutorials/katacoda/command-version-en/index.json, tutorials/katacoda/command-version-en/intro.md, tutorials/katacoda/command-version-en/version.md
=> Arthas version 命令教程

site/src/site/sphinx/_include_html/arthas-tutorials.html, tutorials/katacoda/command-session-cn/arthas-boot.md, tutorials/katacoda/command-session-cn/arthas-demo.md, tutorials/katacoda/command-session-cn/finish.md, tutorials/katacoda/command-session-cn/index.json, tutorials/katacoda/command-session-cn/intro.md, tutorials/katacoda/command-session-cn/session.md, tutorials/katacoda/command-session-en/arthas-boot.md, tutorials/katacoda/command-session-en/arthas-demo.md, tutorials/katacoda/command-session-en/finish.md, tutorials/katacoda/command-session-en/index.json, tutorials/katacoda/command-session-en/intro.md, tutorials/katacoda/command-session-en/session.md
=> Arthas session 命令教程

tutorials/katacoda/command-quit-stop-cn/arthas-boot.md, tutorials/katacoda/command-quit-stop-cn/arthas-demo.md, tutorials/katacoda/command-quit-stop-cn/finish.md, tutorials/katacoda/command-quit-stop-cn/index.json, tutorials/katacoda/command-quit-stop-cn/intro.md, tutorials/katacoda/command-quit-stop-cn/quit-stop.md, tutorials/katacoda/command-quit-stop-en/arthas-boot.md, tutorials/katacoda/command-quit-stop-en/arthas-demo.md, tutorials/katacoda/command-quit-stop-en/finish.md, tutorials/katacoda/command-quit-stop-en/index.json, tutorials/katacoda/command-quit-stop-en/intro.md, tutorials/katacoda/command-quit-stop-en/quit-stop.md
=> Arthas quit-stop 命令教程

site/src/site/sphinx/echo.md, site/src/site/sphinx/en/echo.md, tutorials/katacoda/command-echo-cn/arthas-boot.md, tutorials/katacoda/command-echo-cn/arthas-demo.md, tutorials/katacoda/command-echo-cn/echo.md, tutorials/katacoda/command-echo-cn/finish.md, tutorials/katacoda/command-echo-cn/index.json, tutorials/katacoda/command-echo-cn/intro.md, tutorials/katacoda/command-echo-en/arthas-boot.md, tutorials/katacoda/command-echo-en/arthas-demo.md, tutorials/katacoda/command-echo-en/echo.md, tutorials/katacoda/command-echo-en/finish.md, tutorials/katacoda/command-echo-en/index.json, tutorials/katacoda/command-echo-en/intro.md
=> Arthas echo 命令教程

tutorials/katacoda/command-history-cn/arthas-boot.md, tutorials/katacoda/command-history-cn/arthas-demo.md, tutorials/katacoda/command-history-cn/finish.md, tutorials/katacoda/command-history-cn/history.md, tutorials/katacoda/command-history-cn/index.json, tutorials/katacoda/command-history-cn/intro.md, tutorials/katacoda/command-history-en/arthas-boot.md, tutorials/katacoda/command-history-en/arthas-demo.md, tutorials/katacoda/command-history-en/finish.md, tutorials/katacoda/command-history-en/history.md, tutorials/katacoda/command-history-en/index.json, tutorials/katacoda/command-history-en/intro.md
=> Arthas history 命令教程

site/src/site/sphinx/cat.md, site/src/site/sphinx/en/cat.md, tutorials/katacoda/command-cat-cn/arthas-boot.md, tutorials/katacoda/command-cat-cn/arthas-demo.md, tutorials/katacoda/command-cat-cn/cat.md, tutorials/katacoda/command-cat-cn/finish.md, tutorials/katacoda/command-cat-cn/index.json, tutorials/katacoda/command-cat-cn/intro.md, tutorials/katacoda/command-cat-en/arthas-boot.md, tutorials/katacoda/command-cat-en/arthas-demo.md, tutorials/katacoda/command-cat-en/cat.md, tutorials/katacoda/command-cat-en/finish.md, tutorials/katacoda/command-cat-en/index.json, tutorials/katacoda/command-cat-en/intro.md
=> Arthas cat 命令教程

site/src/site/sphinx/en/tee.md, site/src/site/sphinx/tee.md, tutorials/katacoda/command-tee-cn/arthas-boot.md, tutorials/katacoda/command-tee-cn/arthas-demo.md, tutorials/katacoda/command-tee-cn/finish.md, tutorials/katacoda/command-tee-cn/index.json, tutorials/katacoda/command-tee-cn/intro.md, tutorials/katacoda/command-tee-cn/tee.md, tutorials/katacoda/command-tee-en/arthas-boot.md, tutorials/katacoda/command-tee-en/arthas-demo.md, tutorials/katacoda/command-tee-en/finish.md, tutorials/katacoda/command-tee-en/index.json, tutorials/katacoda/command-tee-en/intro.md, tutorials/katacoda/command-tee-en/tee.md
=> Arthas tee 命令教程

site/src/site/sphinx/en/grep.md, tutorials/katacoda/command-grep-cn/arthas-boot.md, tutorials/katacoda/command-grep-cn/arthas-demo.md, tutorials/katacoda/command-grep-cn/finish.md, tutorials/katacoda/command-grep-cn/grep.md, tutorials/katacoda/command-grep-cn/index.json, tutorials/katacoda/command-grep-cn/intro.md, tutorials/katacoda/command-grep-en/arthas-boot.md, tutorials/katacoda/command-grep-en/arthas-demo.md, tutorials/katacoda/command-grep-en/finish.md, tutorials/katacoda/command-grep-en/grep.md, tutorials/katacoda/command-grep-en/index.json, tutorials/katacoda/command-grep-en/intro.md
=> Arthas grep 命令教程

site/src/site/sphinx/_include_html/arthas-tutorials.html
=> 更新现有教程网页链接

core/pom.xml, pom.xml
repackage netty of arhtas-core.  
required module: https://github.com/hengyunabc/arthas-repackage-deps/pull/1
=> repackage netty

tutorials/katacoda/command-plaintext-cn/arthas-boot.md, tutorials/katacoda/command-plaintext-cn/arthas-demo.md, tutorials/katacoda/command-plaintext-cn/finish.md, tutorials/katacoda/command-plaintext-cn/index.json, tutorials/katacoda/command-plaintext-cn/intro.md, tutorials/katacoda/command-plaintext-cn/plaintext.md, tutorials/katacoda/command-plaintext-en/arthas-boot.md, tutorials/katacoda/command-plaintext-en/arthas-demo.md, tutorials/katacoda/command-plaintext-en/finish.md, tutorials/katacoda/command-plaintext-en/index.json, tutorials/katacoda/command-plaintext-en/intro.md, tutorials/katacoda/command-plaintext-en/plaintext.md
=> Arthas plaintext 命令教程

site/src/site/sphinx/options.md, tutorials/katacoda/command-options-cn/arthas-boot.md, tutorials/katacoda/command-options-cn/arthas-demo.md, tutorials/katacoda/command-options-cn/finish.md, tutorials/katacoda/command-options-cn/index.json, tutorials/katacoda/command-options-cn/intro.md, tutorials/katacoda/command-options-cn/options.md, tutorials/katacoda/command-options-en/arthas-boot.md, tutorials/katacoda/command-options-en/arthas-demo.md, tutorials/katacoda/command-options-en/finish.md, tutorials/katacoda/command-options-en/index.json, tutorials/katacoda/command-options-en/intro.md, tutorials/katacoda/command-options-en/options.md
=> Arthas options 命令教程

tutorials/katacoda/command-getstatic-cn/arthas-boot.md, tutorials/katacoda/command-getstatic-cn/arthas-demo.md, tutorials/katacoda/command-getstatic-cn/finish.md, tutorials/katacoda/command-getstatic-cn/getstatic.md, tutorials/katacoda/command-getstatic-cn/index.json, tutorials/katacoda/command-getstatic-cn/intro.md, tutorials/katacoda/command-getstatic-en/arthas-boot.md, tutorials/katacoda/command-getstatic-en/arthas-demo.md, tutorials/katacoda/command-getstatic-en/finish.md, tutorials/katacoda/command-getstatic-en/getstatic.md, tutorials/katacoda/command-getstatic-en/index.json, tutorials/katacoda/command-getstatic-en/intro.md
=> Arthas getstatic 命令教程

site/src/site/sphinx/monitor.md, tutorials/katacoda/command-monitor-cn/arthas-boot.md, tutorials/katacoda/command-monitor-cn/arthas-demo.md, tutorials/katacoda/command-monitor-cn/finish.md, tutorials/katacoda/command-monitor-cn/index.json, tutorials/katacoda/command-monitor-cn/intro.md, tutorials/katacoda/command-monitor-cn/monitor.md, tutorials/katacoda/command-monitor-en/arthas-boot.md, tutorials/katacoda/command-monitor-en/arthas-demo.md, tutorials/katacoda/command-monitor-en/finish.md, tutorials/katacoda/command-monitor-en/index.json, tutorials/katacoda/command-monitor-en/intro.md, tutorials/katacoda/command-monitor-en/monitor.md
=> Arthas monitor 命令教程

tutorials/katacoda/command-stack-cn/arthas-boot.md, tutorials/katacoda/command-stack-cn/arthas-demo.md, tutorials/katacoda/command-stack-cn/finish.md, tutorials/katacoda/command-stack-cn/index.json, tutorials/katacoda/command-stack-cn/intro.md, tutorials/katacoda/command-stack-cn/stack.md, tutorials/katacoda/command-stack-en/arthas-boot.md, tutorials/katacoda/command-stack-en/arthas-demo.md, tutorials/katacoda/command-stack-en/finish.md, tutorials/katacoda/command-stack-en/index.json, tutorials/katacoda/command-stack-en/intro.md, tutorials/katacoda/command-stack-en/stack.md
=> Arthas stack 命令教程

site/src/site/sphinx/en/mbean.md, site/src/site/sphinx/mbean.md, tutorials/katacoda/command-mbean-cn/arthas-boot.md, tutorials/katacoda/command-mbean-cn/arthas-demo.md, tutorials/katacoda/command-mbean-cn/finish.md, tutorials/katacoda/command-mbean-cn/index.json, tutorials/katacoda/command-mbean-cn/intro.md, tutorials/katacoda/command-mbean-cn/mbean.md, tutorials/katacoda/command-mbean-cn/start-demo.md, tutorials/katacoda/command-mbean-en/arthas-boot.md, tutorials/katacoda/command-mbean-en/arthas-demo.md, tutorials/katacoda/command-mbean-en/finish.md, tutorials/katacoda/command-mbean-en/index.json, tutorials/katacoda/command-mbean-en/intro.md, tutorials/katacoda/command-mbean-en/mbean.md, tutorials/katacoda/command-mbean-en/start-demo.md
=> Arthas mbean 命令教程

tutorials/katacoda/command-tt-cn/arthas-boot.md, tutorials/katacoda/command-tt-cn/arthas-demo.md, tutorials/katacoda/command-tt-cn/finish.md, tutorials/katacoda/command-tt-cn/index.json, tutorials/katacoda/command-tt-cn/intro.md, tutorials/katacoda/command-tt-cn/tt.md, tutorials/katacoda/command-tt-en/arthas-boot.md, tutorials/katacoda/command-tt-en/arthas-demo.md, tutorials/katacoda/command-tt-en/finish.md, tutorials/katacoda/command-tt-en/index.json, tutorials/katacoda/command-tt-en/intro.md, tutorials/katacoda/command-tt-en/tt.md
=> Arthas tt 命令教程

site/src/site/sphinx/trace.md, tutorials/katacoda/command-trace-cn/arthas-boot.md, tutorials/katacoda/command-trace-cn/arthas-demo.md, tutorials/katacoda/command-trace-cn/finish.md, tutorials/katacoda/command-trace-cn/index.json, tutorials/katacoda/command-trace-cn/intro.md, tutorials/katacoda/command-trace-cn/trace.md, tutorials/katacoda/command-trace-en/arthas-boot.md, tutorials/katacoda/command-trace-en/arthas-demo.md, tutorials/katacoda/command-trace-en/finish.md, tutorials/katacoda/command-trace-en/index.json, tutorials/katacoda/command-trace-en/intro.md, tutorials/katacoda/command-trace-en/trace.md
=> Arthas trace 命令教程

site/src/site/sphinx/heapdump.md, tutorials/katacoda/command-heapdump-cn/arthas-boot.md, tutorials/katacoda/command-heapdump-cn/arthas-demo.md, tutorials/katacoda/command-heapdump-cn/finish.md, tutorials/katacoda/command-heapdump-cn/heapdump.md, tutorials/katacoda/command-heapdump-cn/index.json, tutorials/katacoda/command-heapdump-cn/intro.md, tutorials/katacoda/command-heapdump-en/arthas-boot.md, tutorials/katacoda/command-heapdump-en/arthas-demo.md, tutorials/katacoda/command-heapdump-en/finish.md, tutorials/katacoda/command-heapdump-en/heapdump.md, tutorials/katacoda/command-heapdump-en/index.json, tutorials/katacoda/command-heapdump-en/intro.md
=> Arthas heapdump 命令教程

site/src/site/sphinx/watch.md, tutorials/katacoda/command-watch-cn/arthas-boot.md, tutorials/katacoda/command-watch-cn/arthas-demo.md, tutorials/katacoda/command-watch-cn/finish.md, tutorials/katacoda/command-watch-cn/index.json, tutorials/katacoda/command-watch-cn/intro.md, tutorials/katacoda/command-watch-cn/watch.md, tutorials/katacoda/command-watch-en/arthas-boot.md, tutorials/katacoda/command-watch-en/arthas-demo.md, tutorials/katacoda/command-watch-en/finish.md, tutorials/katacoda/command-watch-en/index.json, tutorials/katacoda/command-watch-en/intro.md, tutorials/katacoda/command-watch-en/watch.md
=> Arthas watch 命令教程

site/src/site/sphinx/en/web-console.md, site/src/site/sphinx/web-console.md, tutorials/katacoda/case-web-console-cn/arthas-boot.md, tutorials/katacoda/case-web-console-cn/arthas-demo.md, tutorials/katacoda/case-web-console-cn/finish.md, tutorials/katacoda/case-web-console-cn/index.json, tutorials/katacoda/case-web-console-cn/intro.md, tutorials/katacoda/case-web-console-cn/web-console.md, tutorials/katacoda/case-web-console-en/arthas-boot.md, tutorials/katacoda/case-web-console-en/arthas-demo.md, tutorials/katacoda/case-web-console-en/finish.md, tutorials/katacoda/case-web-console-en/index.json, tutorials/katacoda/case-web-console-en/intro.md, tutorials/katacoda/case-web-console-en/web-console.md
增加web console 案例在线教程并增加文字教程的网页链接
=> Arthas web console 案例教程

site/src/site/sphinx/dump.md, site/src/site/sphinx/en/dump.md, tutorials/katacoda/command-dump-cn/arthas-boot.md, tutorials/katacoda/command-dump-cn/arthas-demo.md, tutorials/katacoda/command-dump-cn/dump.md, tutorials/katacoda/command-dump-cn/finish.md, tutorials/katacoda/command-dump-cn/index.json, tutorials/katacoda/command-dump-cn/intro.md, tutorials/katacoda/command-dump-en/arthas-boot.md, tutorials/katacoda/command-dump-en/arthas-demo.md, tutorials/katacoda/command-dump-en/dump.md, tutorials/katacoda/command-dump-en/finish.md, tutorials/katacoda/command-dump-en/index.json, tutorials/katacoda/command-dump-en/intro.md
=> Arthas dump 命令教程

tutorials/katacoda/case-get-spring-context-cn/arthas-boot.md, tutorials/katacoda/case-get-spring-context-cn/case-get-spring-context.md, tutorials/katacoda/case-get-spring-context-cn/finish.md, tutorials/katacoda/case-get-spring-context-cn/index.json, tutorials/katacoda/case-get-spring-context-cn/intro.md, tutorials/katacoda/case-get-spring-context-cn/start-demo.md, tutorials/katacoda/case-get-spring-context-en/arthas-boot.md, tutorials/katacoda/case-get-spring-context-en/case-get-spring-context.md, tutorials/katacoda/case-get-spring-context-en/finish.md, tutorials/katacoda/case-get-spring-context-en/index.json, tutorials/katacoda/case-get-spring-context-en/intro.md, tutorials/katacoda/case-get-spring-context-en/start-demo.md
=> Arthas 获取Spring Context 案例教程

tutorials/katacoda/case-http-401-cn/arthas-boot.md, tutorials/katacoda/case-http-401-cn/case-http-401.md, tutorials/katacoda/case-http-401-cn/finish.md, tutorials/katacoda/case-http-401-cn/index.json, tutorials/katacoda/case-http-401-cn/intro.md, tutorials/katacoda/case-http-401-cn/start-demo.md, tutorials/katacoda/case-http-401-en/arthas-boot.md, tutorials/katacoda/case-http-401-en/case-http-401.md, tutorials/katacoda/case-http-401-en/case-watch-method-exception.md, tutorials/katacoda/case-http-401-en/finish.md, tutorials/katacoda/case-http-401-en/index.json, tutorials/katacoda/case-http-401-en/intro.md, tutorials/katacoda/case-http-401-en/start-demo.md
=> Arthas 排查HTTP请求返回401 案例教程

site/src/site/sphinx/en/ognl.md, site/src/site/sphinx/ognl.md, tutorials/katacoda/command-ognl-cn/arthas-boot.md, tutorials/katacoda/command-ognl-cn/case-logger-config-problem.md, tutorials/katacoda/command-ognl-cn/case-ognl-update-logger-level.md, tutorials/katacoda/command-ognl-cn/finish.md, tutorials/katacoda/command-ognl-cn/index.json, tutorials/katacoda/command-ognl-cn/intro.md, tutorials/katacoda/command-ognl-cn/ognl.md, tutorials/katacoda/command-ognl-cn/start-demo.md, tutorials/katacoda/command-ognl-en/arthas-boot.md, tutorials/katacoda/command-ognl-en/case-logger-config-problem.md, tutorials/katacoda/command-ognl-en/case-ognl-update-logger-level.md, tutorials/katacoda/command-ognl-en/finish.md, tutorials/katacoda/command-ognl-en/index.json, tutorials/katacoda/command-ognl-en/intro.md, tutorials/katacoda/command-ognl-en/ognl.md, tutorials/katacoda/command-ognl-en/start-demo.md
=> Arthas ognl 命令教程

client/src/main/java/com/taobao/arthas/client/TelnetConsole.java
resolve bash terminal hanging after run arthas-boot.jar.
=> fix terminal hanging #1412

client/src/main/java/com/taobao/arthas/client/TelnetConsole.java
restore terminal settings, fix issue #1412
=> restore terminal flags, fix hanging issue #1412

tutorials/katacoda/case-jad-mc-redefine-cn/arthas-boot.md, tutorials/katacoda/case-jad-mc-redefine-cn/case-jad-mc-redefine.md, tutorials/katacoda/case-jad-mc-redefine-cn/finish.md, tutorials/katacoda/case-jad-mc-redefine-cn/index.json, tutorials/katacoda/case-jad-mc-redefine-cn/intro.md, tutorials/katacoda/case-jad-mc-redefine-cn/start-demo.md, tutorials/katacoda/case-jad-mc-redefine-en/arthas-boot.md, tutorials/katacoda/case-jad-mc-redefine-en/case-jad-mc-redefine.md, tutorials/katacoda/case-jad-mc-redefine-en/finish.md, tutorials/katacoda/case-jad-mc-redefine-en/index.json, tutorials/katacoda/case-jad-mc-redefine-en/intro.md, tutorials/katacoda/case-jad-mc-redefine-en/start-demo.md
=> Arthas 热更新代码 案例教程

tutorials/katacoda/case-classloader-cn/arthas-boot.md, tutorials/katacoda/case-classloader-cn/case-classloader.md, tutorials/katacoda/case-classloader-cn/finish.md, tutorials/katacoda/case-classloader-cn/index.json, tutorials/katacoda/case-classloader-cn/intro.md, tutorials/katacoda/case-classloader-cn/start-demo.md, tutorials/katacoda/case-classloader-en/arthas-boot.md, tutorials/katacoda/case-classloader-en/case-classloader.md, tutorials/katacoda/case-classloader-en/finish.md, tutorials/katacoda/case-classloader-en/index.json, tutorials/katacoda/case-classloader-en/intro.md, tutorials/katacoda/case-classloader-en/start-demo.md
增加理解Spring Boot应用的ClassLoader结构案例在线教程
=> Arthas 理解Spring Boot应用的ClassLoader结构 案例教程

tutorials/katacoda/case-ognl-update-logger-level-cn/arthas-boot.md, tutorials/katacoda/case-ognl-update-logger-level-cn/case-ognl-update-logger-level.md, tutorials/katacoda/case-ognl-update-logger-level-cn/finish.md, tutorials/katacoda/case-ognl-update-logger-level-cn/index.json, tutorials/katacoda/case-ognl-update-logger-level-cn/intro.md, tutorials/katacoda/case-ognl-update-logger-level-cn/start-demo.md, tutorials/katacoda/case-ognl-update-logger-level-en/arthas-boot.md, tutorials/katacoda/case-ognl-update-logger-level-en/case-ognl-update-logger-level.md, tutorials/katacoda/case-ognl-update-logger-level-en/finish.md, tutorials/katacoda/case-ognl-update-logger-level-en/index.json, tutorials/katacoda/case-ognl-update-logger-level-en/intro.md, tutorials/katacoda/case-ognl-update-logger-level-en/start-demo.md
=> Arthas 动态更新应用Logger Level 案例教程

site/src/site/sphinx/en/logger.md, site/src/site/sphinx/logger.md, tutorials/katacoda/command-logger-cn/arthas-boot.md, tutorials/katacoda/command-logger-cn/finish.md, tutorials/katacoda/command-logger-cn/index.json, tutorials/katacoda/command-logger-cn/intro.md, tutorials/katacoda/command-logger-cn/logger.md, tutorials/katacoda/command-logger-cn/start-demo.md, tutorials/katacoda/command-logger-en/arthas-boot.md, tutorials/katacoda/command-logger-en/finish.md, tutorials/katacoda/command-logger-en/index.json, tutorials/katacoda/command-logger-en/intro.md, tutorials/katacoda/command-logger-en/logger.md, tutorials/katacoda/command-logger-en/start-demo.md
=> Arthas logger 命令教程

site/src/site/sphinx/_include_html/arthas-tutorials.html, site/src/site/sphinx/en/profiler.md, site/src/site/sphinx/profiler.md, tutorials/katacoda/command-profiler-cn/arthas-boot.md, tutorials/katacoda/command-profiler-cn/arthas-demo.md, tutorials/katacoda/command-profiler-cn/finish.md, tutorials/katacoda/command-profiler-cn/index.json, tutorials/katacoda/command-profiler-cn/intro.md, tutorials/katacoda/command-profiler-cn/profiler.md, tutorials/katacoda/command-profiler-en/arthas-boot.md, tutorials/katacoda/command-profiler-en/arthas-demo.md, tutorials/katacoda/command-profiler-en/finish.md, tutorials/katacoda/command-profiler-en/index.json, tutorials/katacoda/command-profiler-en/intro.md, tutorials/katacoda/command-profiler-en/profiler.md
=> Arthas profiler 命令教程

site/src/site/sphinx/en/mc.md, site/src/site/sphinx/en/redefine.md, site/src/site/sphinx/mc.md, site/src/site/sphinx/redefine.md, tutorials/katacoda/command-mc-redefine-cn/arthas-boot.md, tutorials/katacoda/command-mc-redefine-cn/case-jad-mc-redefine.md, tutorials/katacoda/command-mc-redefine-cn/finish.md, tutorials/katacoda/command-mc-redefine-cn/index.json, tutorials/katacoda/command-mc-redefine-cn/intro.md, tutorials/katacoda/command-mc-redefine-cn/mc.md, tutorials/katacoda/command-mc-redefine-cn/redefine.md, tutorials/katacoda/command-mc-redefine-cn/start-demo.md, tutorials/katacoda/command-mc-redefine-en/arthas-boot.md, tutorials/katacoda/command-mc-redefine-en/case-jad-mc-redefine.md, tutorials/katacoda/command-mc-redefine-en/finish.md, tutorials/katacoda/command-mc-redefine-en/index.json, tutorials/katacoda/command-mc-redefine-en/intro.md, tutorials/katacoda/command-mc-redefine-en/mc.md, tutorials/katacoda/command-mc-redefine-en/redefine.md, tutorials/katacoda/command-mc-redefine-en/start-demo.md
增加mc-redefine命令在线教程并增加文字教程的网页链接
=> Arthas mc-redefine 命令教程

site/src/site/sphinx/en/sm.md, site/src/site/sphinx/sm.md, tutorials/katacoda/command-sm-cn/arthas-boot.md, tutorials/katacoda/command-sm-cn/arthas-demo.md, tutorials/katacoda/command-sm-cn/finish.md, tutorials/katacoda/command-sm-cn/index.json, tutorials/katacoda/command-sm-cn/intro.md, tutorials/katacoda/command-sm-cn/sm.md, tutorials/katacoda/command-sm-en/arthas-boot.md, tutorials/katacoda/command-sm-en/arthas-demo.md, tutorials/katacoda/command-sm-en/finish.md, tutorials/katacoda/command-sm-en/index.json, tutorials/katacoda/command-sm-en/intro.md, tutorials/katacoda/command-sm-en/sm.md
=> Arthas sm 命令教程

site/src/site/sphinx/en/http-api.md, site/src/site/sphinx/http-api.md
add get java app classpath case of http api
=> add get java app classpath case of http api

core/src/main/java/com/taobao/arthas/core/command/klass100/ClassLoaderCommand.java, core/src/main/java/com/taobao/arthas/core/command/model/ClassLoaderModel.java, core/src/main/java/com/taobao/arthas/core/command/view/ClassLoaderView.java, site/src/site/sphinx/classloader.md, site/src/site/sphinx/en/classloader.md
Make classloader support matching classloader by class name using `--classLoaderClass` just as ognl does.
Signed-off-by: Hollow Man <hollowman186@vip.qq.com>
=> Classloader support matching classloader by class name.

tutorials/katacoda/case-logger-config-problem-cn/arthas-boot.md, tutorials/katacoda/case-logger-config-problem-cn/case-logger-config-problem.md, tutorials/katacoda/case-logger-config-problem-cn/finish.md, tutorials/katacoda/case-logger-config-problem-cn/index.json, tutorials/katacoda/case-logger-config-problem-cn/intro.md, tutorials/katacoda/case-logger-config-problem-cn/start-demo.md, tutorials/katacoda/case-logger-config-problem-en/arthas-boot.md, tutorials/katacoda/case-logger-config-problem-en/case-logger-config-problem.md, tutorials/katacoda/case-logger-config-problem-en/finish.md, tutorials/katacoda/case-logger-config-problem-en/index.json, tutorials/katacoda/case-logger-config-problem-en/intro.md, tutorials/katacoda/case-logger-config-problem-en/start-demo.md
=> Arthas 排查logger冲突问题 案例教程

site/src/site/sphinx/classloader.md, site/src/site/sphinx/en/classloader.md, tutorials/katacoda/command-classloader-cn/arthas-boot.md, tutorials/katacoda/command-classloader-cn/classloader.md, tutorials/katacoda/command-classloader-cn/finish.md, tutorials/katacoda/command-classloader-cn/index.json, tutorials/katacoda/command-classloader-cn/intro.md, tutorials/katacoda/command-classloader-cn/start-demo.md, tutorials/katacoda/command-classloader-en/arthas-boot.md, tutorials/katacoda/command-classloader-en/classloader.md, tutorials/katacoda/command-classloader-en/finish.md, tutorials/katacoda/command-classloader-en/index.json, tutorials/katacoda/command-classloader-en/intro.md, tutorials/katacoda/command-classloader-en/start-demo.md
增加classloader命令在线教程并增加文字教程的网页链接
=> Arthas classloader 命令教程

site/src/site/sphinx/_include_html/arthas-tutorials.html
Signed-off-by: hollowman6 <hollowman186@vip.qq.com>
=> Fix website

core/src/main/java/com/taobao/arthas/core/command/klass100/SearchClassCommand.java, core/src/main/java/com/taobao/arthas/core/command/klass100/SearchMethodCommand.java, core/src/main/java/com/taobao/arthas/core/command/model/SearchClassModel.java, core/src/main/java/com/taobao/arthas/core/command/model/SearchMethodModel.java, core/src/main/java/com/taobao/arthas/core/command/view/SearchClassView.java, core/src/main/java/com/taobao/arthas/core/command/view/SearchMethodView.java, site/src/site/sphinx/en/sc.md, site/src/site/sphinx/en/sm.md, site/src/site/sphinx/sc.md, site/src/site/sphinx/sm.md
Make sc/sm support matching classloader by class name using --classLoaderClass just as ognl and classloader do.
=> Add --classLoaderClass for sc/sm

tutorials/katacoda/command-classloader-cn/classloader.md, tutorials/katacoda/command-classloader-en/classloader.md, tutorials/katacoda/command-sc-cn/sc.md, tutorials/katacoda/command-sc-en/sc.md, tutorials/katacoda/command-sm-cn/sm.md, tutorials/katacoda/command-sm-en/sm.md
=> Update sc/sm Online Tutorial for classLoaderClass

core/src/main/java/com/taobao/arthas/core/command/klass100/ClassLoaderCommand.java
当hashCode或者classLoaderClass参数不为空时，先查找classloader实例，后面的方法直接使用这个实例
Signed-off-by: Hollow Man <hollowman186@vip.qq.com>
=> Optimize --classLoaderClass #1428

tutorials/katacoda/arthas-advanced-cn/case-classloader.md, tutorials/katacoda/arthas-advanced-en/case-classloader.md
=> Classloader using --classLoaderClass in Advanced tutorial

CONTRIBUTING.md, README.md, README_CN.md, tutorials/katacoda/README.md, tutorials/katacoda/README_CN.md
=> Add guides for using and contributing

core/src/main/java/com/taobao/arthas/core/command/logger/LoggerCommand.java, core/src/main/java/com/taobao/arthas/core/command/model/LoggerModel.java, core/src/main/java/com/taobao/arthas/core/command/view/LoggerView.java, site/src/site/sphinx/en/logger.md, site/src/site/sphinx/logger.md, tutorials/katacoda/command-logger-cn/logger.md, tutorials/katacoda/command-logger-en/logger.md
=> Add --classLoaderClass for logger

bytekit/src/main/java/com/taobao/arthas/bytekit/utils/AsmUtils.java, core/src/main/java/com/taobao/arthas/core/advisor/Enhancer.java
Fix issue: https://github.com/alibaba/arthas/issues/1510
Solution:
* Copy origin class constant pool, reducing instrumented class constant changes, avoiding massive growth of metaspace (it should be a bug)
=> Fix metaspace OOM problem when trace large method

core/src/main/java/com/taobao/arthas/core/Arthas.java
fix issue: https://github.com/alibaba/arthas/issues/1519
ignore attach agent error of mismatching jdks:  jdk 7/8 <-> jdk 11/15
=> fix boot error of mismatching jdk

.gitignore, agent/pom.xml, arthas-agent-attach/pom.xml, arthas-spring-boot-starter/pom.xml, boot/pom.xml, bytekit/pom.xml, client/pom.xml, common/pom.xml, core/pom.xml, demo/pom.xml, memorycompiler/pom.xml, packaging/pom.xml, pom.xml, site/pom.xml, spy/pom.xml, testcase/pom.xml, tunnel-client/pom.xml, tunnel-server/pom.xml
优化maven版本管理，通过 revision 统一管理版本号
=> feature: optimize version management

core/src/main/java/com/taobao/arthas/core/command/view/MBeanView.java
Fixes: https://github.com/alibaba/arthas/issues/1644
=> fix NullPointerException in MBeanView

core/src/main/java/com/taobao/arthas/core/advisor/Enhancer.java
1.reset重置增强类的时候，这个创建的transformer经验证未能起到作用，删除并不影响reset功能
=> Remove the useless resetClassFileTransformer in Enhancer

tunnel-server/src/main/java/com/alibaba/arthas/tunnel/server/app/configuration/ArthasProperties.java, tunnel-server/src/main/java/com/alibaba/arthas/tunnel/server/app/web/DetailAPIController.java, tunnel-server/src/main/resources/application.properties
fix ArthasProperties word error:enableDetatilPages -> enableDetailPages
=> fix ArthasProperties word error:enableDetatilPages -> enableDetailPages

site/src/site/sphinx/en/idea-plugin.md, site/src/site/sphinx/idea-plugin.md
=> update arthas idea help link

README.md
spcifically added a $ in front of the command to give a prompt symbol.
=> adding a $ in front of the command

README_CN.md
=> doc: /retransform url format

core/src/main/java/com/taobao/arthas/core/util/SearchUtils.java
```
java.lang.NullPointerException: null
at com.taobao.arthas.core.util.SearchUtils.searchClass(SearchUtils.java:34)
at com.taobao.arthas.core.util.SearchUtils.searchClass(SearchUtils.java:45)
at com.taobao.arthas.core.util.SearchUtils.searchClass(SearchUtils.java:51)
at com.taobao.arthas.core.util.SearchUtils.searchClass(SearchUtils.java:55)
at com.taobao.arthas.core.command.klass100.SearchClassCommand.process(SearchClassCommand.java:128)
at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
at …
```
=> fix: support for websphere 8.5(IBM jvm 1.7)

core/src/main/java/com/taobao/arthas/core/server/ArthasBootstrap.java, core/src/main/java/com/taobao/arthas/core/util/LogUtil.java, core/src/test/java/com/taobao/arthas/core/util/LogUtilTest.java
修复logFile路径在Window中可能展示为：C:\Users\80280631/logs/arthas/arthas.log 的问题
=> Fix:修复logFile路径在window中展示的问题

core/src/main/java/com/taobao/arthas/core/util/ObjectUtils.java
=> Optimize string splicing.

core/src/main/resources/com/taobao/arthas/core/http/index.html, tunnel-server/src/main/resources/static/index.html
webconsole修复resize event在websocket关闭情况下报错的bug
=> bugfix: webconsole修复resize event在websocket关闭情况下报错的bug

site/src/site/sphinx/en/faq.md, site/src/site/sphinx/faq.md
=> Fix skywalking doc url

tunnel-server/src/main/java/com/alibaba/arthas/tunnel/server/cluster/RedisTunnelClusterStore.java
Also, hashSet is not orderedSet, thus it is not that safe to pass it directly to redis's keys function, especially you need the order of return value.
you can change it to LinkedSet but I think ArrayList is a good choice.
=> potential NPE in RedisTunnelClusterStore.

tunnel-server/src/main/java/com/alibaba/arthas/tunnel/server/RelayHandler.java
Remove repeated conditional judgments.
=> Remove repeated conditional judgments.

core/src/main/java/com/taobao/arthas/core/advisor/AdviceListener.java, core/src/main/java/com/taobao/arthas/core/advisor/AdviceWeaver.java
=> Correct mismatched comments.

bin/as.sh
=> fix: spelling error

core/pom.xml
https://github.com/alibaba/arthas/issues/2090
=> shade fastjson

core/src/main/resources/com/taobao/arthas/core/http/index.html, core/src/main/resources/com/taobao/arthas/core/http/xterm.js
修改Mac 谷歌浏览器 最后一行命令显示 https://github.com/alibaba/arthas/issues/2125
=> fix:mac chrome 最后一行命令不显示

core/src/main/java/com/taobao/arthas/core/command/view/TraceView.java
=> fix the issue#1528

tunnel-server/src/main/java/com/alibaba/arthas/tunnel/server/TunnelServer.java
What is the purpose of the change
Strengthening the code
Brief changelog
No effect
=> Strengthen the code

site/src/site/sphinx/en/thread.md, site/src/site/sphinx/thread.md, tutorials/katacoda/command-thread-cn/CPU-ratios-calculate.md, tutorials/katacoda/command-thread-en/CPU-ratios-calculate.md
=> docs: update obsolete link in thread.md

site/docs/.vuepress/config.js, site/docs/.vuepress/configs/head.js, site/docs/.vuepress/plugins/vuepress-plugin-loadVersion/index.js, site/docs/.vuepress/theme/components/HomeBadges.vue, site/docs/.vuepress/theme/components/HomeUserBoards.vue, site/docs/.vuepress/theme/components/NavbarBrand.vue, site/docs/.vuepress/theme/index.js, site/package-lock.json, site/package.json, site/yarn.lock
1. 在导航栏添加版本标签
2. 接入 DocSearch 插件  [Close #2231]
3. 修复 star/fork 数据获取不正确 [Close #2235]
4. 修改元数据中的错误
=> docs(style/plugin): add a version tag to the navbar and add the DocSearch plugin

site/docs/.vuepress/client.js, site/docs/.vuepress/config.js, site/docs/.vuepress/styles/index.scss, site/docs/.vuepress/theme/components/Badge.vue, site/docs/.vuepress/theme/components/RightMenu.vue, site/package-lock.json, site/package.json, site/yarn.lock
1. 修复 `badge` fork 数据偶尔不对的情况
2. 修复访问不存在 sidebar 中的路由时不能正常渲染 sidebar 的情况
3. 添加平滑滚动
=> fix(docs): fix badge component

site/docs/.vuepress/client.js
修改 addOldDocsContributors 函数调用逻辑，避免同个页面多次调用
=> fix: solved duplicate run addOldDocsContributors in same page

web-ui/arthasWebConsole/ui/src/stores/resTransform.ts, web-ui/arthasWebConsole/ui/src/views/async/Watch.vue
* 手写的tree组件性能不佳，加上展示效果与代码折叠不太一致，只能移除掉递归的tree组件以及对文本的返回数据的解析
=> perf(web ui):remove tree component in watch

web-ui/arthasWebConsole/vite.config.ts
=> fix(web ui):support relative paths

core/src/main/java/com/taobao/arthas/core/command/basic1000/JFRCommand.java
=> reformat JFRCommand

common/src/main/java/com/taobao/arthas/common/AnsiLog.java
=> fix AnsiLog format NullPointerException

boot/src/main/java/com/taobao/arthas/boot/Bootstrap.java
=> remove useless param

core/src/main/java/com/taobao/arthas/core/env/ArthasEnvironment.java
根据注释可知配置优先级：  System Env > System Properties 
根据这里的设计可知： System Env > System Properties 
https://github.com/alibaba/arthas/issues/986#issuecomment-569223934
但是根据当前代码实现来看，目前的配置优先级是有问题的: System Properties  >  System Env
=> fix the priority of environment properties

core/src/main/java/com/taobao/arthas/core/command/monitor200/PerfCounterCommand.java, site/docs/doc/perfcounter.md, site/docs/en/doc/perfcounter.md, tutorials/katacoda/command-perfcounter-cn/perfcounter.md, tutorials/katacoda/command-perfcounter-en/perfcounter.md
see https://github.com/alibaba/arthas/issues/2364
=> doc: 当jdk版本大于9时 perfcount命令提示增加相关的启动参数

arthas-vmtool/pom.xml, common/src/main/java/com/taobao/arthas/common/OSUtils.java, common/src/main/java/com/taobao/arthas/common/VmToolUtils.java, packaging/src/main/assembly/assembly.xml
=> 补充针对linux系统的非主流架构的编译构建使用支持

core/src/main/java/com/taobao/arthas/core/server/ArthasBootstrap.java, core/src/main/java/com/taobao/arthas/core/util/UserStatUtil.java, tunnel-server/src/main/java/com/alibaba/arthas/tunnel/server/app/web/StatController.java
回复 https://github.com/alibaba/arthas/issues/2480
=> 数据回报添加agentId

site/docs/doc/dump.md, site/docs/doc/getstatic.md, site/docs/en/doc/dump.md, site/docs/en/doc/getstatic.md
修改平台名称 Katacoda 修改为 Killercoda
=> fix: update platform name in Arthas tutorials

core/src/main/java/com/taobao/arthas/core/command/model/SystemEnvModel.java
see https://github.com/alibaba/arthas/issues/2619
=> feat: sysenv sorted by property key

core/src/main/java/com/taobao/arthas/core/command/monitor200/ThreadSampler.java
=> 缺失注解@Override补齐

core/src/main/java/com/taobao/arthas/core/command/klass100/DumpClassCommand.java, core/src/main/java/com/taobao/arthas/core/command/klass100/JadCommand.java, core/src/main/java/com/taobao/arthas/core/util/FileUtils.java
1 JadCommand 增加指定路径的参数检查
2 修复JadCommand参数描述的拼写错误
=> check directory for JadCommand and fix typos

pom.xml
#2530
* Set `spring-boot.version`  from 2.7.14 to 2.7.15 in `pom.xml`
* Set `spring-boot3.version`  from 3.0.6 to 3.1.3 in `pom.xml`
=> Bump spring-boot3 to 3.1.3 and spring-boot to 2.7.15

pom.xml
#2530
* Set zt-zip version to 1.16 in `pom.xml`
=> Bump zt-zip from 1.14 to 1.16

pom.xml
#2530
* Set netty.version to 4.1.97.Final in `pom.xml`
=> Bump netty from 4.1.92.Final to 4.1.97.Final

pom.xml
#2530
* Set byte-buddy version to 1.14.8 in `pom.xml`
* Set byte-buddy-agent version to 1.14.8 in `pom.xml`
=> Bump byte-buddy and byte-buddy-agent from 1.14.4 to 1.14.8

pom.xml
#2530
* Set fastjson2 version to 2.0.40 in `pom.xml`
=> Bump fastjson2 from 2.0.31 to 2.0.40

core/src/main/java/com/taobao/arthas/core/command/monitor200/ProfilerCommand.java
=> Fix profiler command live option

core/src/main/java/com/taobao/arthas/core/shell/cli/CompletionUtils.java
=> support windows file separator for file path completion
